// Endpoints from Vite env only — no fallbacks. `.env.local` is gitignored and generated by
// `node scripts/webEnv.mjs` (a later task) from apps/infra-cdk/cdk-outputs.json, the same
// source the e2e workspace reads. A missing endpoint fails loudly at import time instead of
// the app silently pointing requests at "undefined".
export class ConfigError extends Error {
  constructor(
    readonly code: string,
    message?: string,
  ) {
    super(message ?? code);
    this.name = "ConfigError";
  }
}

const requireEnv = (key: "VITE_HTTP_URL" | "VITE_WS_URL"): string => {
  const value = import.meta.env[key];
  if (!value) {
    throw new ConfigError("missing-env", `${key} is not set — run \`node scripts/webEnv.mjs\` to generate .env.local, or set it before starting the dev server.`);
  }
  return value;
};

export const config: { readonly httpUrl: string; readonly wsUrl: string } = {
  httpUrl: requireEnv("VITE_HTTP_URL"),
  wsUrl: requireEnv("VITE_WS_URL"),
};
