// The prod strokes migration (spec 2026-07-31 §4). This script WRITES TO A PRODUCTION TABLE.
//
// It is a DRY RUN unless `--write` is passed. It NEVER DELETES ANYTHING — there is no
// DeleteCommand, no BatchWrite, no removal path anywhere in this file, and there is no flag that
// creates one. PROD IS NEVER WIPED. The only writes it can perform are:
//
//   * the 15 records of spec §4 — rounds-table events and snapshot archives whose stored shape
//     predates the strokes rename — each put back as the WHOLE item it was read as, with only its
//     `event` / `archive` attribute replaced. Never a reconstructed item: a snapshot carries
//     `finalizedAt` and whatever else it carries, and rebuilding an item from the fields you
//     happened to think of is how an attribute disappears silently.
//   * `--restore <file>` — putting the exported images back, verbatim.
//
// Two rules, imported from scripts/prodStrokesMigration.mjs and defined nowhere else: in a
// participant seat `courseHandicap` becomes `strokes`, and `participant-handicap-set` becomes
// `participant-strokes-set` with the same field rename inside it. Both are guarded on the old
// shape actually being present, so the whole migration is idempotent — a re-run is a no-op and an
// interrupted run is just a shorter next run. The instrument that WRITES prod and the instrument
// that CHECKS it (checkProdParses.mjs) share that one module precisely so they cannot drift.
//
// Safety, in the order it happens:
//
//   1. Every transformed record is PARSED with HEAD's own schema before a single Put is issued.
//      A record that would not parse is never written and stops the run. That makes it
//      structurally impossible for this script to write a record the app cannot read.
//   2. In `--write` mode, every item of all four tables is exported to
//      `prod-backup-<stage>-<timestamp>.json` BEFORE any write. If the export fails for any
//      reason the run exits before writing. The export is taken from the very same scan the
//      migration is computed from, so the `before` images on disk are exactly the images being
//      transformed.
//      A dry run does NOT write an export — it says so — because the protection that matters is
//      an export taken in the same invocation as the write, not a stale one from an earlier run.
//   3. Events are written first and snapshots last. The snapshots table has a stream and the
//      projector is its consumer, so a snapshot write re-derives that round's record lines; it
//      goes last, once everything it folds is already consistent.
//   4. If the parse gate rejects a record in `--write` mode, the export has already been taken
//      and nothing else has happened. An export file with no migration is the expected residue
//      of that path, not a sign something half-ran.
//
// The projections and core tables are READ (for the export) and never written. The 8 record lines
// are not migrated — they are regenerated by the projector off the snapshot writes (spec §4).
//
//   node scripts/migrateProdStrokes.mjs [--stage prod] [--write]
//   node scripts/migrateProdStrokes.mjs [--stage prod] --restore <file> [--write]
import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
// `migrateEvent` / `migrateArchive` are the only two entry points a stored item can need — the
// seat rule is applied INSIDE them — so `seat` itself is deliberately not imported here. Every
// rename this script performs comes out of that module and none of it is restated in this file.
import { migrateEvent, migrateArchive, changed } from "./prodStrokesMigration.mjs";

const require = createRequire(new URL("../packages/adapters-dynamodb/package.json", import.meta.url));
const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");
// ScanCommand to read, PutCommand to write. Nothing that deletes is imported, so nothing that
// deletes can be called.
const { DynamoDBDocumentClient, ScanCommand, PutCommand } = require("@aws-sdk/lib-dynamodb");

const argv = process.argv;
const stage = argv.includes("--stage") ? argv[argv.indexOf("--stage") + 1] : "prod";
const write = argv.includes("--write");
const restoreFile = argv.includes("--restore") ? argv[argv.indexOf("--restore") + 1] : undefined;

if (argv.includes("--restore") && (restoreFile === undefined || restoreFile.startsWith("--"))) {
  console.error("error: --restore needs the path of an export file written by an earlier --write run.");
  process.exit(1);
}

let contracts;
try {
  contracts = await import("../packages/contracts/dist/index.js");
} catch (error) {
  console.error("error: could not load HEAD's schemas from packages/contracts/dist — run `pnpm build` first.");
  console.error(String(error));
  process.exit(1);
}
const { roundEventSchema, roundArchiveSchema } = contracts;
if (roundEventSchema === undefined || roundArchiveSchema === undefined) {
  console.error("error: packages/contracts/dist loaded but exports no roundEventSchema/roundArchiveSchema — the build is stale. Run `pnpm build`.");
  process.exit(1);
}

const roundsTable = `swng-rounds-${stage}`;
const snapshotsTable = `swng-snapshots-${stage}`;
const projectionsTable = `swng-projections-${stage}`;
const coreTable = `swng-core-${stage}`;

const client = DynamoDBDocumentClient.from(new DynamoDBClient({ region: "us-east-1", profile: process.env.AWS_PROFILE ?? "swng" }));

const scanAll = async (tableName) => {
  const items = [];
  let exclusiveStartKey;
  do {
    const page = await client.send(new ScanCommand({ TableName: tableName, ExclusiveStartKey: exclusiveStartKey }));
    items.push(...(page.Items ?? []));
    exclusiveStartKey = page.LastEvaluatedKey;
  } while (exclusiveStartKey);
  return items;
};

// A generic leaf-path diff of the before and after images — deliberately NOT a hand-written
// description of what the rename does. It reports what actually changed between two values, so it
// stays honest if the transform ever changes and it cannot become a second, drifting statement of
// the rules.
const leaves = (value, prefix, out) => {
  if (value !== null && typeof value === "object") {
    for (const [k, v] of Object.entries(value)) leaves(v, prefix === "" ? k : `${prefix}.${k}`, out);
    return out;
  }
  out.set(prefix, value);
  return out;
};

const describeChange = (before, after) => {
  const a = leaves(before, "", new Map());
  const b = leaves(after, "", new Map());
  const lines = [];
  for (const [path, value] of a) {
    if (!b.has(path)) lines.push(`- ${path} = ${JSON.stringify(value)}`);
    else if (JSON.stringify(b.get(path)) !== JSON.stringify(value)) lines.push(`~ ${path}: ${JSON.stringify(value)} -> ${JSON.stringify(b.get(path))}`);
  }
  for (const [path, value] of b) if (!a.has(path)) lines.push(`+ ${path} = ${JSON.stringify(value)}`);
  return lines;
};

console.log(`swng prod strokes migration — stage ${stage} — ${write ? "*** WRITE MODE ***" : "DRY RUN"}${restoreFile !== undefined ? ` — RESTORE from ${restoreFile}` : ""}`);
console.log("this script never deletes anything; prod is never wiped\n");

// --- restore ----------------------------------------------------------------------------------
// Verbatim: every item in the export goes back exactly as it was read. It does NOT delete items
// created after the export was taken — a restore puts back what it holds, it does not reset a
// table to a moment in time, and pretending otherwise would be the more dangerous instrument.

if (restoreFile !== undefined) {
  let backup;
  try {
    backup = JSON.parse(readFileSync(restoreFile, "utf8"));
  } catch (error) {
    console.error(`error: could not read the export file ${restoreFile}: ${String(error)}`);
    process.exit(1);
  }
  if (backup?.tables === undefined) {
    console.error(`error: ${restoreFile} is not an export written by this script (no \`tables\` key).`);
    process.exit(1);
  }
  console.log(`export taken ${backup.takenAt} from stage ${backup.stage}`);
  if (backup.stage !== stage) {
    console.error(`error: the export was taken from stage "${backup.stage}" but --stage says "${stage}". Refusing to write one stage's data into another.`);
    process.exit(1);
  }

  let restored = 0;
  for (const [tableName, items] of Object.entries(backup.tables)) {
    console.log(`  ${write ? "restoring" : "would restore"} ${items.length} item(s) into ${tableName}`);
    if (!write) continue;
    for (const item of items) {
      await client.send(new PutCommand({ TableName: tableName, Item: item }));
      restored += 1;
    }
  }
  console.log(write ? `\nrestored ${restored} item(s) verbatim.` : "\nDRY RUN — nothing written. Re-run with --write to restore.");
  process.exit(0);
}

// --- read -------------------------------------------------------------------------------------

const roundsItems = await scanAll(roundsTable);
const snapshotItems = await scanAll(snapshotsTable);
console.log(`read ${roundsItems.length} item(s) from ${roundsTable} and ${snapshotItems.length} item(s) from ${snapshotsTable}\n`);

// --- export (write mode only, before anything is written) ---------------------------------------

if (write) {
  const projectionItems = await scanAll(projectionsTable);
  const coreItems = await scanAll(coreTable);
  const path = `prod-backup-${stage}-${new Date().toISOString().replace(/[:.]/g, "-")}.json`;
  const tables = {
    [roundsTable]: roundsItems,
    [snapshotsTable]: snapshotItems,
    [projectionsTable]: projectionItems,
    [coreTable]: coreItems,
  };
  const total = Object.values(tables).reduce((n, items) => n + items.length, 0);
  try {
    writeFileSync(path, JSON.stringify({ stage, takenAt: new Date().toISOString(), tables }, undefined, 1));
  } catch (error) {
    console.error(`error: the export failed, so nothing will be written: ${String(error)}`);
    process.exit(1);
  }
  console.log(`EXPORT: ${total} item(s) from all 4 tables -> ${path}`);
  for (const [tableName, items] of Object.entries(tables)) console.log(`         ${items.length.toString().padStart(4)}  ${tableName}`);
  console.log("");
} else {
  // Announced, never silent. A skipped step that logs nothing is indistinguishable from one that
  // ran, and the person reading this transcript later has to be able to tell which happened.
  console.log(`SKIPPED the export (dry run): nothing is being written, and an export is only protection if it is taken in the same run as the write.\n`);
}

// --- transform --------------------------------------------------------------------------------

const records = [];
const problems = [];

for (const item of roundsItems) {
  if (item.event === undefined) continue;
  let after;
  try {
    after = migrateEvent(item.event);
  } catch (error) {
    problems.push({ key: `${roundsTable}  ${item.pk} ${item.sk}`, detail: `the transform threw: ${String(error)}` });
    continue;
  }
  if (!changed(item.event, after)) continue;
  records.push({
    table: roundsTable,
    key: `${item.pk} ${item.sk}`,
    kind: `${item.event.kind} -> ${after.kind}`,
    before: item.event,
    after,
    item: { ...item, event: after },
    schema: roundEventSchema,
    order: 0, // events first
  });
}

for (const item of snapshotItems) {
  let after;
  try {
    after = migrateArchive(item.archive);
  } catch (error) {
    problems.push({ key: `${snapshotsTable}  ${item.pk}`, detail: `the transform threw: ${String(error)}` });
    continue;
  }
  if (!changed(item.archive, after)) continue;
  records.push({
    table: snapshotsTable,
    key: String(item.pk),
    kind: "archive",
    before: item.archive,
    after,
    item: { ...item, archive: after },
    schema: roundArchiveSchema,
    order: 1, // snapshots last — the stream fires off these
  });
}

// --- the parse gate, before any write -----------------------------------------------------------

for (const record of records) {
  const result = record.schema.safeParse(record.after);
  if (result.success) continue;
  const issues = result.error.issues.map((issue) => (issue.path.length > 0 ? `${issue.path.join(".")}: ${issue.message}` : issue.message));
  problems.push({ key: `${record.table}  ${record.key}`, detail: `the transformed record does not parse at HEAD — ${issues.join("; ")}` });
}

if (problems.length > 0) {
  console.error(`REFUSING TO WRITE — ${problems.length} record(s) could not be transformed into something HEAD can read:\n`);
  for (const problem of problems) console.error(`  ${problem.key}\n      ${problem.detail}`);
  console.error("\nNothing was written.");
  process.exit(1);
}

// --- the plan ---------------------------------------------------------------------------------

if (records.length === 0) {
  console.log("Nothing to do — every record already carries the current shape (the transform is idempotent, so this is what a second run looks like). Nothing was written.");
  process.exit(0);
}

records.sort((a, b) => a.order - b.order || (a.key < b.key ? -1 : 1));

console.log(`${records.length} record(s) to migrate — every one of them parses at HEAD:\n`);
for (const record of records) {
  console.log(`  ${record.table}  ${record.key}   [${record.kind}]`);
  for (const line of describeChange(record.before, record.after)) console.log(`      ${line}`);
}
console.log("");

if (!write) {
  console.log(`DRY RUN — nothing written. ${records.length} record(s) would be put back whole, with only the \`event\`/\`archive\` attribute replaced.`);
  console.log(`Re-run with --write to migrate. The projections and core tables are read for the export and never written.`);
  process.exit(0);
}

// --- write ------------------------------------------------------------------------------------
// Whole items, events before snapshots. `records` is already sorted into that order.

let written = 0;
let writtenEvents = 0;
let writtenSnapshots = 0;
for (const record of records) {
  try {
    await client.send(new PutCommand({ TableName: record.table, Item: record.item }));
  } catch (error) {
    console.error(`\nFAILED writing ${record.table} ${record.key}: ${String(error)}`);
    console.error(`${written} record(s) were written before this failure. The transform is idempotent — fix the cause and re-run; it will pick up exactly what is left.`);
    process.exit(1);
  }
  written += 1;
  if (record.table === roundsTable) writtenEvents += 1;
  else writtenSnapshots += 1;
  console.log(`  wrote ${record.table}  ${record.key}`);
}

console.log(`\nWROTE ${written} record(s): ${writtenEvents} event item(s), then ${writtenSnapshots} snapshot item(s).`);
console.log(`${projectionsTable} and ${coreTable} were read for the export and NOT written — the record lines re-derive from the snapshot stream.`);
console.log(`Nothing was deleted.`);
